version: '3.9'
services:
    webapp:
      container_name: iot_webapp
      restart: on-failure
      build:
        context: ./webapp
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ./db:/app/db
        - ./webapp:/app
      links:
        - mosquitto
      depends_on:
        - transmisor
      environment:
        - PYTHONUNBUFFERED=1
    transmisor:
      container_name: iot_transmisor
      restart: on-failure
      build:
        context: ./transmisor
        dockerfile: Dockerfile
      links:
        - mosquitto
      depends_on:
        - mosquitto
        - simulador
      environment:
        - PYTHONUNBUFFERED=1
      volumes:
        - ./db:/app/db
    simulador:
      container_name: iot_simulador
      restart: on-failure
      build:
        context: ./simulador
        dockerfile: Dockerfile
      volumes:
        - ./simulador/log:/app/log
      depends_on:
        - mosquitto
      links:
        - mosquitto
    mosquitto:
      image: eclipse-mosquitto
      container_name: iot_mosquitto
      restart: always
      build:
        context: ./mosquitto
        dockerfile: Dockerfile
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./volumes/mosquitto/data:/mosquitto/data
        - ./volumes/mosquitto/log:/mosquitto/log